name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: '/home/runner/.local/share/pnpm'
          key: 'pnpm-deps'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: enable corepack
        run: corepack enable

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: install firebase-tools 
        run: npm install -g firebase-tools

      - name: deploy
        env:
          FIREBASE_SERVICE_PK: ${{ secrets.FIREBASE_SERVICE_PK }}
          GOOGLE_APPLICATION_CREDENTIALS: service.json
        run: |
          echo $FIREBASE_SERVICE_PK > $GOOGLE_APPLICATION_CREDENTIALS
          ./node_modules/.bin/firebase projects:list
          # ./node_modules/.bin/firebase use grammar-tutor-510b2 -- is it desirable to make sure the project?
          ./node_modules/.bin/firebase deploy --only hosting 
