name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: '/home/runner/.local/share/pnpm'
          key: 'pnpm-deps'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: enable corepack
        run: corepack enable

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: install firebase-tools 
        run: npm install -g firebase-tools

      - name: deploy
        env:
          FIREBASE_SERVICE_PK: ${{ secrets.FIREBASE_SERVICE_PK }}
          GOOGLE_APPLICATION_CREDENTIALS: service.json
        run: |
          echo $FIREBASE_SERVICE_PK > $GOOGLE_APPLICATION_CREDENTIALS
          firebase projects:list
          firebase use  grammar-tutor
          firebase deploy --only hosting 
